server:
  port: 3000

logging:
  level:
    root: error
    org.springframework.web: ERROR
    com.example.auth0demoapplication: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: GdzV8F8mfvKmw9CkGmgOYBkQaN0pqN51
            client-secret: p0Rnva2r4u27oKL9HWiWc9Ex2ys9Aq0-DbjWy2aWHOFwN7XwT9l8MxhITjZMsL2Q
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            issuer-uri: https://dev-cxqcbn18bkf6d12v.us.auth0.com

